# generated by datamodel-codegen:
#   filename:  GforceStore-notow4pikzczbpjg42gytvbuci-production.json
#   timestamp: 2025-09-26T04:19:43+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, Field


class VisitDay(BaseModel):
    name: str
    checked: bool


class AdditionalRepItem(BaseModel):
    rep_cover: str
    last_name: str
    from_date: str
    to_date: str
    rep_cover_username: str
    first_name: str


class ContactItem(BaseModel):
    name: str
    position: str
    phone: str
    email: str


class Note(BaseModel):
    datetime: str
    notes: str


class SalesRepNote(BaseModel):
    datetime: str
    notes: str


class ModelItem(BaseModel):
    store_manager: str
    support_rep_username: str
    retailer_name: str
    trade_drive_trough: str
    visit_time: str
    country: str
    visit_days: List[VisitDay]
    state: str
    field_version: float = Field(..., alias='_version')
    territory: str
    whare_sfs: str
    additionalRep: List[AdditionalRepItem]
    region: str
    id: str
    support_status: str
    senior_rep_username: str
    field__typename: str = Field(..., alias='__typename')
    field_lastChangedAt: float = Field(..., alias='_lastChangedAt')
    store_grade: str
    store_id: str
    senior_status: str
    contact: List[ContactItem]
    createdAt: str
    address: str
    visit_freq: str
    updatedAt: str
    store_size: str
    mob_number: str
    store_manager_email: str
    visit_start_week_no: str
    store_name: str
    store_status: Optional[str] = None
    notes: Optional[List[Note]] = None
    sales_status: Optional[str] = None
    sales_rep_notes: Optional[List[SalesRepNote]] = None
    sales_rep_username: Optional[str] = None


class Model(BaseModel):
    __root__: List[ModelItem]
