-- This is the output from `read_json_auto`

CREATE TABLE call_cycle_raw (
  __typename VARCHAR,
  call_status VARCHAR,
  _lastChangedAt DOUBLE,
  call_time VARCHAR,
  end_date VARCHAR,
  stores STRUCT (
    store_id VARCHAR,
    mins_per_visit VARCHAR,
    anotherDis BOOLEAN,
    supplier_username VARCHAR,
    store_name VARCHAR,
    checked BOOLEAN,
    disabled BOOLEAN,
    "label" VARCHAR,
    "value" VARCHAR,
    frequency VARCHAR,
    supplier VARCHAR
  ) [],
  createdAt VARCHAR,
  retailer VARCHAR,
  call_cycle_name VARCHAR,
  country STRUCT ("value" VARCHAR, "label" VARCHAR) [],
  call_id VARCHAR,
  state STRUCT ("value" VARCHAR, "label" VARCHAR) [],
  _version DOUBLE,
  call_cycle_freq VARCHAR,
  start_date VARCHAR,
  updatedAt VARCHAR,
  supplier_username VARCHAR,
  id UUID,
  supplier_name VARCHAR
);

CREATE TABLE stores_raw (
  store_manager VARCHAR,
  support_rep_username VARCHAR,
  retailer_name VARCHAR,
  trade_drive_trough VARCHAR,
  visit_time VARCHAR,
  country VARCHAR,
  visit_days STRUCT ("name" VARCHAR, checked BOOLEAN) [],
  state VARCHAR,
  _version DOUBLE,
  territory VARCHAR,
  whare_sfs VARCHAR,
  additionalRep STRUCT (
    rep_cover VARCHAR,
    last_name VARCHAR,
    from_date VARCHAR,
    to_date VARCHAR,
    rep_cover_username VARCHAR,
    first_name VARCHAR
  ) [],
  region VARCHAR,
  id UUID,
  support_status VARCHAR,
  senior_rep_username VARCHAR,
  __typename VARCHAR,
  _lastChangedAt DOUBLE,
  store_grade VARCHAR,
  store_id VARCHAR,
  senior_status VARCHAR,
  contact STRUCT (
    "name" VARCHAR,
    "position" VARCHAR,
    phone VARCHAR,
    email VARCHAR
  ) [],
  createdAt VARCHAR,
  address VARCHAR,
  visit_freq VARCHAR,
  updatedAt VARCHAR,
  store_size VARCHAR,
  mob_number VARCHAR,
  store_manager_email VARCHAR,
  visit_start_week_no VARCHAR,
  store_name VARCHAR,
  store_status VARCHAR,
  notes STRUCT (datetime VARCHAR, notes VARCHAR) [],
  sales_status VARCHAR,
  sales_rep_notes STRUCT (datetime VARCHAR, notes VARCHAR) [],
  sales_rep_username VARCHAR
);


CREATE TABLE task_raw (
  documentAdd STRUCT (
    requiredDoc BOOLEAN,
    "document" VARCHAR,
    notes VARCHAR,
    uploaded BOOLEAN,
    signed BOOLEAN,
    localUri VARCHAR,
    mimeType VARCHAR,
    "key" VARCHAR
  ) [],
  cover_rep_first_name VARCHAR,
  support_rep_last_name VARCHAR,
  endDate VARCHAR,
  cannot_complete_photos JSON [],
  retailer_name VARCHAR,
  cannot_complete_reason VARCHAR,
  country STRUCT ("value" VARCHAR, "label" VARCHAR) [],
  state STRUCT ("value" VARCHAR, "label" VARCHAR) [],
  logo_img VARCHAR,
  cover_rep_last_name VARCHAR,
  docs_from_rep JSON [],
  startDate VARCHAR,
  SK VARCHAR,
  supplier_name VARCHAR,
  taskDate VARCHAR,
  __typename VARCHAR,
  callCycle STRUCT (
    call_cycle_freq VARCHAR,
    storeList STRUCT (store_id VARCHAR, store_name VARCHAR) [],
    call_cycle_name VARCHAR,
    call_status VARCHAR,
    retailer VARCHAR,
    call_id VARCHAR
  ) [],
  _lastChangedAt DOUBLE,
  pause_task_reason VARCHAR,
  store_id VARCHAR,
  task_photos STRUCT (
    task_id VARCHAR,
    client_photos_shareable VARCHAR,
    photo_name VARCHAR,
    task_photos_notes VARCHAR
  ) [],
  time_spent VARCHAR,
  task_name VARCHAR,
  comments_from_rep VARCHAR,
  support_rep_first_name VARCHAR,
  task_description VARCHAR,
  delegated BOOLEAN,
  week_number VARCHAR,
  cover_rep_type VARCHAR,
  task_id VARCHAR,
  senior_rep_first_name VARCHAR,
  recurring BOOLEAN,
  full_company_name VARCHAR,
  PK VARCHAR,
  photos_from_rep VARCHAR [],
  store_name VARCHAR,
  support_rep_username VARCHAR,
  task_type VARCHAR,
  created_date VARCHAR,
  week_startDate VARCHAR,
  supplier_id VARCHAR,
  stores STRUCT (
    store_id VARCHAR,
    store_name VARCHAR,
    checked BOOLEAN,
    state VARCHAR,
    "label" VARCHAR,
    "value" VARCHAR
  ),
  _version DOUBLE,
  task_priority VARCHAR,
  feedback_reassign VARCHAR,
  task_approval VARCHAR,
  id UUID,
  taskDateISO8601 DATE,
  cannot_complete_comments VARCHAR,
  senior_rep_username VARCHAR,
  cannot_complete_documents JSON [],
  "action" JSON,
  questions STRUCT (
    question VARCHAR,
    client_shareable VARCHAR,
    Answers VARCHAR [],
    additionShareable VARCHAR,
    question_shareable BOOLEAN,
    answer_from_rep VARCHAR
  ) [],
  record_time VARCHAR,
  rep_images_cannot_complete STRUCT (
    bucket VARCHAR,
    localUri VARCHAR,
    mimeType VARCHAR,
    region VARCHAR,
    "key" VARCHAR,
    isUploaded VARCHAR
  ) [],
  fine_line VARCHAR,
  oneOff BOOLEAN,
  rep_documents JSON [],
  task_approval_notes VARCHAR,
  visit_freq VARCHAR,
  cover_rep_username VARCHAR,
  task_status VARCHAR,
  task_comments STRUCT (
    task_id VARCHAR,
    "comment" VARCHAR,
    task_comments_notes VARCHAR,
    client_comments_shareable VARCHAR
  ) [],
  updatedAt VARCHAR,
  recurringValue VARCHAR,
  senior_rep_last_name VARCHAR,
  push_task_comments VARCHAR,
  rep_images STRUCT (
    bucket VARCHAR,
    localUri VARCHAR,
    mimeType VARCHAR,
    region VARCHAR,
    "key" VARCHAR,
    isUploaded VARCHAR
  ) [],
  solved BOOLEAN,
  delegated_to_sup_rep VARCHAR,
  delegated_comments VARCHAR
);
