# generated by datamodel-codegen:
#   filename:  GforceCallCycle-notow4pikzczbpjg42gytvbuci-production.json
#   timestamp: 2025-09-26T04:19:35+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, Field


class Store(BaseModel):
    store_id: str
    mins_per_visit: Optional[str] = None
    anotherDis: Optional[bool] = None
    supplier_username: Optional[str] = None
    store_name: str
    checked: bool
    disabled: bool
    label: str
    value: str
    frequency: str
    supplier: Optional[str] = None


class CountryItem(BaseModel):
    value: str
    label: str


class StateItem(BaseModel):
    value: str
    label: str


class ModelItem(BaseModel):
    field__typename: str = Field(..., alias='__typename')
    call_status: str
    field_lastChangedAt: float = Field(..., alias='_lastChangedAt')
    call_time: str
    end_date: str
    stores: List[Store]
    createdAt: str
    retailer: str
    call_cycle_name: str
    country: List[CountryItem]
    call_id: str
    state: List[StateItem]
    field_version: float = Field(..., alias='_version')
    call_cycle_freq: str
    start_date: str
    updatedAt: str
    supplier_username: str
    id: str
    supplier_name: str


class Model(BaseModel):
    __root__: List[ModelItem]
